---
# Implement your Pre Workload deployment tasks here
- set_fact:
    ansible_python_interpreter: "/bin/python"

- name: Setup pre-requisite python3 packages
  package:
    state: present
    name:
    - git
    - python3-pip
  become: true

- name: Setup pre-requisite pip3 packages
  pip:
    name:
    - virtualenv
    state: present
    executable: /usr/bin/pip3
  become: true

- name: Copy requirements.txt to target for k8s virtualenv
  copy:
    src: ./files/requirements_k8s.txt
    dest: /tmp/requirements_k8s.txt
  become: true

- name: "Create virtualenv k8s"
  pip:
    requirements: /tmp/requirements_k8s.txt
    virtualenv: "/opt/virtualenvs/k8s"
    virtualenv_site_packages: no
    virtualenv_command: /usr/local/bin/virtualenv
  become: true

- name: Ensure system Python3 has selinux library installed
  pip:
    state: present
    executable: /usr/bin/pip3
    name: selinux
    version: 0.2.1
  become: true

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool
