---
# Implement your Workload removal tasks here

- name: Ensure there is connectivity to OCP cluster as system:admin
  command: oc whoami
  register: whoami
  changed_when: false

- name: Fail if not system:admin
  fail:
    msg: "Not connected to OCP as system:admin"
  when: whoami.stdout != "system:admin"

- name: Ensure required templates are present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0666
  loop:
    - { src: ./templates/subscription.j2, dest: /tmp/subscription.yaml }
    - { src: ./templates/multiClusterHub.j2, dest: /tmp/multiClusterHub.yaml }
    - { src: ./templates/operatorGroup.j2, dest: /tmp/operatorGroup.yaml }

- name: Ensure RHACM MultiClusterHub is absent
  shell: oc -n "{{ ocp4_workload_rhacm_acm_project }}" delete -f /tmp/multiClusterHub.yaml

- name: Ensure RHACM Subscription is absent
  shell: oc -n "{{ ocp4_workload_rhacm_acm_project }}" delete -f /tmp/subscription.yaml

- name: Ensure RHACM OperatorGroup is absent
  shell: oc -n "{{ ocp4_workload_rhacm_acm_project }}" delete -f /tmp/operatorGroup.yaml

- name: Ensure RHACM Namespace is absent
  shell: oc delete namespace "{{ ocp4_workload_rhacm_acm_project }}"

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
