
---
galaxy_info:
  role_name: ocp4-workload-acm-app-policies-lab
  author: Management Integration Team - pit-hybrid@redhat.com
  description: |
    Set up ACM Lab for OpenShift 4.
  license: MIT
  min_ansible_version: 2.8
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
  - acm
dependencies: []