---
- name: Ensure Lab's Git Repository is Cloned
  git:
    repo: "{{ _lab_git_repo }}"
    dest: "/home/{{ _clientvm_student_user }}/{{ _lab_git_clone_dir_name }}"
    version: "{{ _lab_git_repo_branch }}"
  become: true

- name: Ensure Lab's Git Repository Folder has required permissions
  file:
    path: "/home/{{ _clientvm_student_user }}/{{ _lab_git_clone_dir_name }}"
    state: directory
    recurse: yes
    owner: "{{ _clientvm_student_user }}" 
    group: "{{ _clientvm_student_user_group }}"
  become: true

# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool
